sudo: false
language: python
cache: pip
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
script: scripts/runtest.sh
deploy:
  provider: pypi
  user: uncovertruth
  password:
    secure: EbuYCrzrV4X9cJhj832zikWP9KUn6mEpf+/Ajm40amMS2jY5j9sJaLZulf3D+Ff3/I5K2fIjYrzzr+M+UxoD56eg2wfMmn3tvsngtDMhwMU5CCMWKJrcponEmCi5PYwp5lSQgmCjZlgaWS2reSzsDQe4oVS8ivejSUbZgE+o9vk=
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    repo: uncovertruth/py-geohex3
    tags: true
    python: 3.6
